export const INITIAL_DEPARTMENTS = [
  { id: 'unassigned', name: '配置待ち', type: 'pool', posts: [], groups: [] },
  { id: 'retired', name: '退職・転出', type: 'pool', posts: [], groups: [] },
  {
    id: "dept-1", name: "森林整備課", type: "regular",
    posts: [{ id: "p-1", name: "課長" }, { id: "p-2", name: "副課長" }, { id: "p-3", name: "主幹" }],
    groups: [
      { id: "g-1", name: "緑化推進班", posts: [{ id: "gp-1", name: "班長" }] },
      { id: "g-2", name: "治山班", posts: [{ id: "gp-2", name: "班長" }] }
    ]
  }
];

export const INITIAL_EMPLOYEES = [
  { id: "emp-1", employeeNumber: "083259", education: "三重大", hireDate: "1990-04-01", name: "和歌山 豊", birthDate: "1967-12-30", currentGrade: "所属長級", currentTitle: "課長", currentYears: 1, currentSkills: ["1"], currentEmploymentType: "", currentExclude: "", nextGrade: "次長級", nextTitle: "課長", nextYears: 1, nextSkills: [], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: "p-1", currentGroupId: null, currentGroupPostId: null, departmentId: "retired", postId: null, groupId: null, groupPostId: null, note: "", orderCurrent: 1000, orderNext: 1000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-2", employeeNumber: "090565", education: "東京農大", hireDate: "1993-04-01", name: "海南 伸也", birthDate: "1970-05-02", currentGrade: "課長級", currentTitle: "副課長", currentYears: 1, currentSkills: ["1"], currentEmploymentType: "", currentExclude: "", nextGrade: "所属長級", nextTitle: "副課長", nextYears: 2, nextSkills: ["1+1"], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: "p-2", currentGroupId: null, currentGroupPostId: null, departmentId: "dept-1", postId: "p-2", groupId: null, groupPostId: null, note: "", orderCurrent: 2000, orderNext: 2000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-3", employeeNumber: "096512", education: "東京農大", hireDate: "1995-04-01", name: "橋本 孝史", birthDate: "1972-09-25", currentGrade: "課長級", currentTitle: "主幹", currentYears: 2, currentSkills: ["1+1"], currentEmploymentType: "", currentExclude: "", nextGrade: "課長級", nextTitle: "主幹", nextYears: 3, nextSkills: ["1+1+1"], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: "p-3", currentGroupId: null, currentGroupPostId: null, departmentId: "dept-1", postId: "p-3", groupId: null, groupPostId: null, note: "", orderCurrent: 3000, orderNext: 3000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-4", employeeNumber: "098123", education: "京都大", hireDate: "1996-04-01", name: "御坊 伸也", birthDate: "1973-11-12", currentGrade: "補佐級III(補佐兼班長)", currentTitle: "課長補佐兼班長", currentYears: 2, currentSkills: ["2"], currentEmploymentType: "", currentExclude: "", nextGrade: "補佐級III(補佐兼班長)", nextTitle: "課長補佐兼班長", nextYears: 1, nextSkills: [], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: null, currentGroupId: "g-1", currentGroupPostId: "gp-1", departmentId: "unassigned", postId: null, groupId: null, groupPostId: null, note: "", orderCurrent: 4000, orderNext: 4000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-5", employeeNumber: "101788", education: "熊野高", hireDate: "1997-04-01", name: "有田 智雄", birthDate: "1978-11-05", currentGrade: "補佐級II(班長)", currentTitle: "班長", currentYears: 3, currentSkills: ["3"], currentEmploymentType: "", currentExclude: "", nextGrade: "補佐級II(班長)", nextTitle: "班長", nextYears: 4, nextSkills: ["4"], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: null, currentGroupId: "g-2", currentGroupPostId: "gp-2", departmentId: "dept-1", postId: null, groupId: "g-2", groupPostId: "gp-2", note: "", orderCurrent: 5000, orderNext: 5000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-6", employeeNumber: "115678", education: "和歌山大", hireDate: "2005-04-01", name: "新宮 資紀", birthDate: "1982-04-20", currentGrade: "補佐級I(主任)", currentTitle: "主任", currentYears: 4, currentSkills: ["4"], currentEmploymentType: "", currentExclude: "", nextGrade: "補佐級I(主任)", nextTitle: "主任", nextYears: 5, nextSkills: ["5"], nextEmploymentType: "", nextExclude: "", currentDeptId: "dept-1", currentPostId: null, currentGroupId: "g-1", currentGroupPostId: null, departmentId: "dept-1", postId: null, groupId: "g-1", groupPostId: null, note: "", orderCurrent: 6000, orderNext: 6000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
  { id: "emp-7", employeeNumber: "123456", education: "近畿大", hireDate: "2010-04-01", name: "かつらぎ 有香子", birthDate: "1987-08-15", currentGrade: "", currentTitle: "技師", currentYears: 2, currentSkills: ["2"], currentEmploymentType: "", currentExclude: "育休", nextGrade: "", nextTitle: "技師", nextYears: 1, nextSkills: [], nextEmploymentType: "", nextExclude: "育休", currentDeptId: "dept-1", currentPostId: null, currentGroupId: "g-2", currentGroupPostId: null, departmentId: "unassigned", postId: null, groupId: null, groupPostId: null, note: "", orderCurrent: 7000, orderNext: 7000, promoYearDeptHead: "", promoYearDeputyHead: "", promoYearDivHead: "", promoYearSecHead: "", promoYearAssistant3: "", promoYearAssistant2: "", promoYearAssistant1: "", promoYearChief: "" },
];
